name: "vehicle"
platform: "tensorrt_plan"
max_batch_size: 32
dynamic_batching {
    preferred_batch_size: [32]
    max_queue_delay_microseconds: 0
}
input: [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640]
    is_shape_tensor: false
  }
]
output: [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1]
    is_shape_tensor: false
  }
]

instance_group: [
  {
    kind: KIND_GPU
    count: 2
    gpus: [0]
  }
]
